//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `smartHome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package smartHome;

/** @hidden */
public class _ILedLightPrxI extends com.zeroc.Ice._ObjectPrxI implements ILedLightPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
