//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `smartHome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package smartHome;

public class DeviceNotExistsException extends com.zeroc.Ice.UserException
{
    public DeviceNotExistsException()
    {
        this.message = "";
    }

    public DeviceNotExistsException(Throwable cause)
    {
        super(cause);
        this.message = "";
    }

    public DeviceNotExistsException(String message)
    {
        this.message = message;
    }

    public DeviceNotExistsException(String message, Throwable cause)
    {
        super(cause);
        this.message = message;
    }

    public String ice_id()
    {
        return "::smartHome::DeviceNotExistsException";
    }

    public String message;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::smartHome::DeviceNotExistsException", -1, true);
        ostr_.writeString(message);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        message = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -1222540085L;
}
