//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `smartHome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package smartHome;

public enum DeviceType implements java.io.Serializable
{
    RGBWxLEDxLIGHT(0),
    MONOCHROMATICxLEDxLIGHT(1),
    IPV6xNETWORKxMONITOR(2),
    NATxNETWORKxMONITOR(3);

    public int value()
    {
        return _value;
    }

    public static DeviceType valueOf(int v)
    {
        switch(v)
        {
        case 0:
            return RGBWxLEDxLIGHT;
        case 1:
            return MONOCHROMATICxLEDxLIGHT;
        case 2:
            return IPV6xNETWORKxMONITOR;
        case 3:
            return NATxNETWORKxMONITOR;
        }
        return null;
    }

    private DeviceType(int v)
    {
        _value = v;
    }

    public void ice_write(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeEnum(_value, 3);
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, DeviceType v)
    {
        if(v == null)
        {
            ostr.writeEnum(smartHome.DeviceType.RGBWxLEDxLIGHT.value(), 3);
        }
        else
        {
            ostr.writeEnum(v.value(), 3);
        }
    }

    public static DeviceType ice_read(com.zeroc.Ice.InputStream istr)
    {
        int v = istr.readEnum(3);
        return validate(v);
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<DeviceType> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, DeviceType v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.Size))
        {
            ice_write(ostr, v);
        }
    }

    public static java.util.Optional<DeviceType> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.Size))
        {
            return java.util.Optional.of(ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static DeviceType validate(int v)
    {
        final DeviceType e = valueOf(v);
        if(e == null)
        {
            throw new com.zeroc.Ice.MarshalException("enumerator value " + v + " is out of range");
        }
        return e;
    }

    private final int _value;
}
