//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `smartHome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package smartHome;

/**
 * Helper class for marshaling/unmarshaling IpAddresses.
 **/
public final class IpAddressesHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, IpAddress[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                IpAddress.ice_write(ostr, v[i0]);
            }
        }
    }

    public static IpAddress[] read(com.zeroc.Ice.InputStream istr)
    {
        final IpAddress[] v;
        final int len0 = istr.readAndCheckSeqSize(2);
        v = new IpAddress[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = IpAddress.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<IpAddress[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, IpAddress[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            IpAddressesHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<IpAddress[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            IpAddress[] v;
            v = IpAddressesHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
