//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `smartHome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package smartHome;

public class IPv6NetworkMonitor extends NetworkMonitor
{
    public IPv6NetworkMonitor()
    {
        super();
    }

    public IPv6NetworkMonitor(String name, DeviceType deviceType, String serialNumber, NetworkStatus status, short connectedDevicesNo, short networkBandwidth, Ipv6Address[] devices)
    {
        super(name, deviceType, serialNumber, status, connectedDevicesNo, networkBandwidth);
        this.devices = devices;
    }

    public Ipv6Address[] devices;

    public IPv6NetworkMonitor clone()
    {
        return (IPv6NetworkMonitor)super.clone();
    }

    public static String ice_staticId()
    {
        return "::smartHome::IPv6NetworkMonitor";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = 1305782500L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, false);
        Ipv6AddressesHelper.write(ostr_, devices);
        ostr_.endSlice();
        super._iceWriteImpl(ostr_);
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        devices = Ipv6AddressesHelper.read(istr_);
        istr_.endSlice();
        super._iceReadImpl(istr_);
    }
}
