//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `smartHome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package smartHome;

public class MonoChromaticLedLight extends LedLight
{
    public MonoChromaticLedLight()
    {
        super();
        this.mainColor = Color.RED;
    }

    public MonoChromaticLedLight(String name, DeviceType deviceType, String serialNumber, boolean isOn, short brightness, LightMode lightMode, Color mainColor)
    {
        super(name, deviceType, serialNumber, isOn, brightness, lightMode);
        this.mainColor = mainColor;
    }

    public Color mainColor;

    public MonoChromaticLedLight clone()
    {
        return (MonoChromaticLedLight)super.clone();
    }

    public static String ice_staticId()
    {
        return "::smartHome::MonoChromaticLedLight";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -654311801L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, false);
        Color.ice_write(ostr_, mainColor);
        ostr_.endSlice();
        super._iceWriteImpl(ostr_);
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        mainColor = Color.ice_read(istr_);
        istr_.endSlice();
        super._iceReadImpl(istr_);
    }
}
