//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `smartHome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package smartHome;

public class NetworkMonitor extends SmartHomeDevice
{
    public NetworkMonitor()
    {
        super();
        this.status = NetworkStatus.ON;
    }

    public NetworkMonitor(String name, DeviceType deviceType, String serialNumber, NetworkStatus status, short connectedDevicesNo, short networkBandwidth)
    {
        super(name, deviceType, serialNumber);
        this.status = status;
        this.connectedDevicesNo = connectedDevicesNo;
        this.networkBandwidth = networkBandwidth;
    }

    public NetworkStatus status;

    public short connectedDevicesNo;

    public short networkBandwidth;

    public NetworkMonitor clone()
    {
        return (NetworkMonitor)super.clone();
    }

    public static String ice_staticId()
    {
        return "::smartHome::NetworkMonitor";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = 1043993210L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, false);
        NetworkStatus.ice_write(ostr_, status);
        ostr_.writeShort(connectedDevicesNo);
        ostr_.writeShort(networkBandwidth);
        ostr_.endSlice();
        super._iceWriteImpl(ostr_);
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        status = NetworkStatus.ice_read(istr_);
        connectedDevicesNo = istr_.readShort();
        networkBandwidth = istr_.readShort();
        istr_.endSlice();
        super._iceReadImpl(istr_);
    }
}
